# Generated by Django 4.2.4 on 2023-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
